const deck = [
  { value: 2, suit: "Hearts", img: "img/2H.svg" },
  { value: 3, suit: "Hearts", img: "img/3H.svg" },
  { value: 4, suit: "Hearts", img: "img/4H.svg" },
  { value: 5, suit: "Hearts", img: "img/5H.svg" },
  { value: 6, suit: "Hearts", img: "img/6H.svg" },
  { value: 7, suit: "Hearts", img: "img/7H.svg" },
  { value: 8, suit: "Hearts", img: "img/8H.svg" },
  { value: 9, suit: "Hearts", img: "img/9H.svg" },
  { value: 10, suit: "Hearts", img: "img/TH.svg" },
  { value: 10, suit: "Hearts", face: "Jack", img: "img/JH.svg" },
  { value: 10, suit: "Hearts", face: "Queen", img: "img/QH.svg" },
  { value: 10, suit: "Hearts", face: "King", img: "img/KH.svg" },
  { value: 11, suit: "Hearts", face: "Ace", img: "img/AH.svg" },
  { value: 2, suit: "Diamonds", img: "img/2D.svg" },
  { value: 3, suit: "Diamonds", img: "img/3D.svg" },
  { value: 4, suit: "Diamonds", img: "img/4D.svg" },
  { value: 5, suit: "Diamonds", img: "img/5D.svg" },
  { value: 6, suit: "Diamonds", img: "img/6D.svg" },
  { value: 7, suit: "Diamonds", img: "img/7D.svg" },
  { value: 8, suit: "Diamonds", img: "img/8D.svg" },
  { value: 9, suit: "Diamonds", img: "img/9D.svg" },
  { value: 10, suit: "Diamonds", img: "img/TD.svg" },
  { value: 10, suit: "Diamonds", face: "Jack", img: "img/JD.svg" },
  { value: 10, suit: "Diamonds", face: "Queen", img: "img/QD.svg" },
  { value: 10, suit: "Diamonds", face: "King", img: "img/KD.svg" },
  { value: 11, suit: "Diamonds", face: "Ace", img: "img/AD.svg" },
  { value: 2, suit: "Clubs", img: "img/2C.svg" },
  { value: 3, suit: "Clubs", img: "img/3C.svg" },
  { value: 4, suit: "Clubs", img: "img/4C.svg" },
  { value: 5, suit: "Clubs", img: "img/5C.svg" },
  { value: 6, suit: "Clubs", img: "img/6C.svg" },
  { value: 7, suit: "Clubs", img: "img/7C.svg" },
  { value: 8, suit: "Clubs", img: "img/8C.svg" },
  { value: 9, suit: "Clubs", img: "img/9C.svg" },
  { value: 10, suit: "Clubs", img: "img/TC.svg" },
  { value: 10, suit: "Clubs", face: "Jack", img: "img/JC.svg" },
  { value: 10, suit: "Clubs", face: "Queen", img: "img/QC.svg" },
  { value: 10, suit: "Clubs", face: "King", img: "img/KC.svg" },
  { value: 11, suit: "Clubs", face: "Ace", img: "img/AC.svg" },
  { value: 2, suit: "Spades", img: "img/2S.svg" },
  { value: 3, suit: "Spades", img: "img/3S.svg" },
  { value: 4, suit: "Spades", img: "img/4S.svg" },
  { value: 5, suit: "Spades", img: "img/5S.svg" },
  { value: 6, suit: "Spades", img: "img/6S.svg" },
  { value: 7, suit: "Spades", img: "img/7S.svg" },
  { value: 8, suit: "Spades", img: "img/8S.svg" },
  { value: 9, suit: "Spades", img: "img/9S.svg" },
  { value: 10, suit: "Spades", img: "img/TS.svg" },
  { value: 10, suit: "Spades", face: "Jack", img: "img/JS.svg" },
  { value: 10, suit: "Spades", face: "Queen", img: "img/QS.svg" },
  { value: 10, suit: "Spades", face: "King", img: "img/KS.svg" },
  { value: 11, suit: "Spades", face: "Ace", img: "img/AS.svg" },
];

export default deck;
