const deck = [
  { value: 2, suit: "Hearts", img: "" },
  { value: 3, suit: "Hearts", img: "" },
  { value: 4, suit: "Hearts", img: "" },
  { value: 5, suit: "Hearts", img: "" },
  { value: 6, suit: "Hearts", img: "" },
  { value: 7, suit: "Hearts", img: "" },
  { value: 8, suit: "Hearts", img: "" },
  { value: 9, suit: "Hearts", img: "" },
  { value: 10, suit: "Hearts", img: "" },
  { value: 10, suit: "Hearts", face: "Jack", img: "" },
  { value: 10, suit: "Hearts", face: "Queen", img: "" },
  { value: 10, suit: "Hearts", face: "King", img: "" },
  { value: 11, suit: "Hearts", face: "Ace", img: "" },
  { value: 2, suit: "Diamonds", img: "" },
  { value: 3, suit: "Diamonds", img: "" },
  { value: 4, suit: "Diamonds", img: "" },
  { value: 5, suit: "Diamonds", img: "" },
  { value: 6, suit: "Diamonds", img: "" },
  { value: 7, suit: "Diamonds", img: "" },
  { value: 8, suit: "Diamonds", img: "" },
  { value: 9, suit: "Diamonds", img: "" },
  { value: 10, suit: "Diamonds", img: "" },
  { value: 10, suit: "Diamonds", face: "Jack", img: "" },
  { value: 10, suit: "Diamonds", face: "Queen", img: "" },
  { value: 10, suit: "Diamonds", face: "King", img: "" },
  { value: 11, suit: "Diamonds", face: "Ace", img: "" },
  { value: 2, suit: "Clubs", img: "" },
  { value: 3, suit: "Clubs", img: "" },
  { value: 4, suit: "Clubs", img: "" },
  { value: 5, suit: "Clubs", img: "" },
  { value: 6, suit: "Clubs", img: "" },
  { value: 7, suit: "Clubs", img: "" },
  { value: 8, suit: "Clubs", img: "" },
  { value: 9, suit: "Clubs", img: "" },
  { value: 10, suit: "Clubs", img: "" },
  { value: 10, suit: "Clubs", face: "Jack", img: "" },
  { value: 10, suit: "Clubs", face: "Queen", img: "" },
  { value: 10, suit: "Clubs", face: "King", img: "" },
  { value: 11, suit: "Clubs", face: "Ace", img: "" },
  { value: 2, suit: "Spades", img: "" },
  { value: 3, suit: "Spades", img: "" },
  { value: 4, suit: "Spades", img: "" },
  { value: 5, suit: "Spades", img: "" },
  { value: 6, suit: "Spades", img: "" },
  { value: 7, suit: "Spades", img: "" },
  { value: 8, suit: "Spades", img: "" },
  { value: 9, suit: "Spades", img: "" },
  { value: 10, suit: "Spades", img: "" },
  { value: 10, suit: "Spades", face: "Jack", img: "" },
  { value: 10, suit: "Spades", face: "Queen", img: "" },
  { value: 10, suit: "Spades", face: "King", img: "" },
  { value: 11, suit: "Spades", face: "Ace", img: "" },
];

export default deck;
